#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$ROOT_DIR"

CONFIG="${CONFIG:-src/train_configs/local_mac_scale_static_dynamic_vjepa_1k_video_pretrain_F32_256_16f_8192splats.jsonc}"
TRAINER="src/train/train.py"
MODE="${1:-check}"

usage() {
  cat >&2 <<'EOF'
Usage:
  train_scale_static_dynamic_vjepa_1k_video_pretrain.sh check
  train_scale_static_dynamic_vjepa_1k_video_pretrain.sh smoke
  train_scale_static_dynamic_vjepa_1k_video_pretrain.sh train

Environment:
  CONFIG             Override train config path.
  SMOKE_SEQUENCES    Number of manifest rows copied into the smoke manifest. Default: 1.

The default config points at the no-copy 1k manifest generated by:
  PYTHONPATH=src/train uv run python src/dataset_scripts/build_single_video_pretrain_manifest.py

For a materialized frame-clip alternative:
  ./src/train_scripts/build_dynaworld_scale_1k_clip_dataset.sh dry-run
  OVERWRITE_CLIPS=1 ./src/train_scripts/build_dynaworld_scale_1k_clip_dataset.sh build
EOF
}

require_file() {
  local path="$1"
  local label="$2"
  if [[ ! -f "$path" ]]; then
    echo "Missing $label: $path" >&2
    exit 1
  fi
}

config_check() {
  PYTHONPATH=src/train uv run python - "$CONFIG" <<'PY'
import sys
from pathlib import Path

from config_utils import load_config_file
from train_artifacts import write_json
from trainer_registry import resolve_config_for_arch

path = Path(sys.argv[1])
cfg = resolve_config_for_arch(load_config_file(path), path)
manifest = Path(cfg["data"]["manifest_path"])
print(
    "Resolved scale-pretrain config: "
    f"arch={cfg['arch']} "
    f"manifest={manifest} "
    f"load_mode={cfg['data']['train_manifest_load_mode']} "
    f"keep_in_memory={cfg['features']['keep_in_memory']} "
    f"release_extractor_after_prebake={cfg['features']['release_extractor_after_prebake']}"
)
if manifest.exists():
    counts = {}
    with manifest.open(encoding="utf-8") as handle:
        for line in handle:
            if not line.strip():
                continue
            import json

            split = str(json.loads(line).get("split", "train"))
            counts[split] = counts.get(split, 0) + 1
    print(f"Manifest counts: {counts}")
else:
    print(
        f"Manifest is not built yet: {manifest}\n"
        "Regenerate it with: PYTHONPATH=src/train uv run python "
        "src/dataset_scripts/build_single_video_pretrain_manifest.py"
    )
PY
}

write_smoke_config() {
  local tmp_dir="$1"
  local smoke_config="$tmp_dir/smoke_config.json"
  local smoke_manifest="$tmp_dir/manifest.jsonl"
  PYTHONPATH=src/train uv run python - "$CONFIG" "$smoke_config" "$smoke_manifest" "${SMOKE_SEQUENCES:-1}" <<'PY'
import json
import sys
from pathlib import Path

from config_utils import load_config_file

config_path, smoke_config_path, smoke_manifest_path, smoke_sequences = sys.argv[1:5]
smoke_sequences = int(smoke_sequences)
cfg = load_config_file(config_path)
manifest = Path(cfg["data"]["manifest_path"])
if not manifest.exists():
    raise SystemExit(f"Manifest is not built yet: {manifest}")
rows = []
with manifest.open(encoding="utf-8") as handle:
    for line in handle:
        if not line.strip():
            continue
        rows.append(line)
        if len(rows) >= smoke_sequences:
            break
if not rows:
    raise SystemExit(f"Manifest has no rows: {manifest}")
Path(smoke_manifest_path).write_text("".join(rows), encoding="utf-8")
cfg["data"]["manifest_path"] = str(smoke_manifest_path)
cfg["data"]["eval_max_sequences"] = 0
cfg["train"]["steps"] = 1
cfg["logging"]["wandb_run_name"] = f"{cfg['logging']['wandb_run_name']}-smoke"
cfg["logging"]["log_every"] = 1
cfg["logging"]["image_log_every"] = 999
cfg["logging"]["video_log_every"] = 999
cfg["logging"]["always_log_last_step"] = False
cfg["export"] = {"enabled": False}
write_json(Path(smoke_config_path), cfg, sort_keys=False)
print(smoke_config_path)
PY
}

case "$MODE" in
  check)
    require_file "$CONFIG" "config"
    config_check
    ;;
  smoke)
    require_file "$CONFIG" "config"
    require_file "$TRAINER" "trainer"
    tmp_dir="$(mktemp -d -t dynaworld_scale_vjepa_smoke.XXXXXX)"
    trap 'rm -rf "$tmp_dir"' EXIT
    write_smoke_config "$tmp_dir"
    WANDB_MODE=offline PYTHONPATH=src/train uv run python "$TRAINER" "$tmp_dir/smoke_config.json"
    ;;
  train)
    require_file "$CONFIG" "config"
    require_file "$TRAINER" "trainer"
    PYTHONPATH=src/train uv run python "$TRAINER" "$CONFIG"
    ;;
  -h|--help|help)
    usage
    ;;
  *)
    usage
    exit 1
    ;;
esac
